cart/urls.py
from django.urls import path
from .import views

app_name="cart"
urlpatterns = [

    path('cart/', views.cart_add, name='cart_add'),
    # path('cart_show/', views.cart_show, name='cart_show'),
    path('cart_exam_show/', views.cart_exam_show, name='cart_exam_show'),
    path('exam_edit/<str:edit_>/', views.exam_edit, name='exam_edit'),
    path('exam_edit_delete/<int:id>/', views.exam_edit_delete, name='exam_edit_delete'),
    path('exam_delete/<str:delete>/', views.exam_delete, name='exam_delete'),
    path('exam_pdf/<str:e_title>/', views.exam_pdf, name='exam_pdf'),

]

main/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings #add this
from django.conf.urls.static import static #add this
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizbox.urls')),
    path('user/', include("user.urls")),    
    path('question/', include("question.urls")),    
    path('cart/', include("cart.urls")),
    path('testing_and_exam/', include("testing_and_exam.urls")),
    path('forum/', include("forum.urls")),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

question/urls.py
from django.urls import path
from .import views

app_name="question"

urlpatterns = [
    path('question/',views.Question_,name="Question"),
    path('get_lessons/', views.get_lessons, name='get_lessons'),
    path('get_topics/', views.get_topics, name='get_topics'),
    path('article_create/',views.article_create,name="article_create"),
    path('question_detail/<int:id>/', views.question_detail, name='question_detail'),
    path('question_delete/', views.question_delete, name='question_delete'),
    path('like_question/', views.like_question, name='like_question'),
     path('get_like_count/',  views.get_like_count, name='get_like_count'),
    path('show_cart/', views.show_cart, name='show_cart'),
    path('quiz/', views.quiz, name='quiz'),
    path('save_input_value/', views.save_input_value, name='save_input_value'),
    path('get_exam_titles/', views.get_exam_titles, name='get_exam_titles'),
    
    path('exam_save/', views.exam_save, name='exam_save'),
    path('exam_save_2/', views.exam_save_2, name='exam_save_2'),
    path('exam_save_2_cart_delete//<int:id>/', views.exam_save_2_cart_delete, name='exam_save_2_cart_delete'),
    path('question/<int:question_id>/add_comment/', views.add_comment, name='add_comment'),
    # path('get_topics/', views.get_topics, name='get_topics'),
]

cart/models.py
from django.db import models
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render
from question.models import Question
from django.contrib import messages
from django.contrib.auth.models import User

# Create your models here.
class Cart(models.Model):
    author=models.ForeignKey(User,on_delete = models.CASCADE,verbose_name="Sepete Ekleyen")
    exam_items=models.IntegerField(null=True,verbose_name="Soru Id:")
    Lessons=models.CharField(verbose_name="Ders Adı",null=True,max_length=50)
    Question=models.TextField(verbose_name="Soru",null=True)
    Choice_A=models.TextField(verbose_name="A Şıkkı",blank=True, null=True)
    Choice_B=models.TextField(verbose_name="B Şıkkı",blank=True, null=True)
    Choice_C=models.TextField(verbose_name="C Şıkkı",blank=True, null=True)
    Choice_D=models.TextField(verbose_name="D Şıkkı",blank=True, null=True)
    Choice_E=models.TextField(verbose_name="E Şıkkı",blank=True, null=True)
    Answer=models.TextField(verbose_name="Cevap",null=True)
    Classroom=models.CharField(verbose_name="Kaçıncı Sınıf Sorusu?",null=True,blank=False,max_length=10)
    Topics_Name=models.CharField(max_length=100,verbose_name="Konu Adı",null=True)
    Question_Types=models.CharField(verbose_name='SORU TİPLERİ',null=True,max_length=20)
    Level = models.CharField(default="KOLAY", max_length=6, blank=True)
    Question_Image=models.ImageField(upload_to='cart_images/',blank=True, null=True, verbose_name="Soruya Fotoğraf Ekleyin")
    created_date=models.DateTimeField(auto_now=True,verbose_name="Oluşturma Tarihi")
    def __str__(self):
        return  'Kullanıcı={0}, Soru Id={1}'.format(self.author, self.exam_items)#self.title,self.content,self.created_date



class CartExamTitle(models.Model):
    author=models.ForeignKey(User,on_delete = models.CASCADE,verbose_name="Sınavı Adını Oluşturan")# bunu django hazır kullanıcı tablosundan alıyoruz
    exam_title=models.CharField(blank=True, max_length=100,verbose_name="Sınav Adı")
    created_date=models.DateTimeField(auto_now=True,verbose_name="Oluşturma Tarihi")

    def __str__(self):
        return  'Kullanıcı={0}, Sınav Adı={1}'.format(self.author, self.exam_title)
    


cart/views.py
from doctest import Example
from django.shortcuts import get_object_or_404, redirect, render
from cart.models import Cart, CartExamTitle
from django.http import HttpResponse, JsonResponse
from exam.models import Exam
from question.models import Question
from django.db.models import Q
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect

from user.models import Profile

# Create your views here.
def cart_add(request):
    user = get_object_or_404(Profile, author_id=request.user.id)
     
    if request.user.is_authenticated:
        if user.user_types =="Teacher":
            if request.method == 'POST':
                exam_item_id = request.POST.get('user_id')
                Question_Image = request.FILES.get('Question_Image')

                # Assuming the user is logged in
                print("Exam item ID:", exam_item_id)
                product = get_object_or_404(Question, id=exam_item_id)
                # Create a new cart item
                kaydet = Cart.objects.create(
                author=request.user, 
                exam_items=exam_item_id,
                Lessons=product.Lessons,
                Question=product.Question,
                Answer=product.Answer,
                Classroom=product.Classroom,
                Topics_Name=product.Topics_Name,
                Question_Types=product.Question_Types,
                Level=product.Level,
                Question_Image=product.Question_Image,
                Choice_A =product.Choice_A,
                Choice_B =product.Choice_B,
                Choice_C =product.Choice_C,
                Choice_D =product.Choice_D,
                Choice_E =product.Choice_E,
                )
                kaydet.save()
                return JsonResponse({'success': product.Lessons,'Topics_Name': product.Topics_Name,'Level': product.Level})
            return JsonResponse({'success': False})
        else:
            redirect_url = reverse('quizorder:index')  # 'hata_sayfasi' isimli URL'nin adını projenize göre değiştirin
            # Yönlendirme yapın
            return HttpResponseRedirect(redirect_url)
    else:
        redirect_url = reverse('quizorder:index')  # 'hata_sayfasi' isimli URL'nin adını projenize göre değiştirin
        # Yönlendirme yapın
        return HttpResponseRedirect(redirect_url)

# def cart_show(request):
#     cart_shows = Cart.objects.filter(author=request.user).order_by('-created_date')
#     exam_title=CartExamTitle.objects.filter(author=request.user).order_by('-created_date')
#     context={
#         'cart_shows':cart_shows,
#         'exam_title':exam_title
#     }
#     return render(request, 'cart/cart_show.html',context)


def cart_exam_show(request):
    user = get_object_or_404(Profile, author_id=request.user.id)
     
    if request.user.is_authenticated:
        if user.user_types =="Teacher":
    #exam_show = Exam.objects.values('Exam_Title','Topics_Name','id').filter(author=request.user)
    # exam_show = Exam.objects.filter(author=request.user).values('Exam_Title').distinct()
            from django.db.models import Max
            #exam_show = Exam.objects.values('Exam_Title','Topics_Name','id').filter(author=request.user)
            exam_show = Exam.objects.filter(author=request.user).values('Exam_Title').annotate(max_created_date=Max('Created_Date'))
            cnt = exam_show.count()
            context={
                'exam_show':exam_show,
                'cnt':cnt
            }
            return render(request,"cart/exam_show.html",context)
        else:
            redirect_url = reverse('quizorder:index')  # 'hata_sayfasi' isimli URL'nin adını projenize göre değiştirin
            # Yönlendirme yapın
            return HttpResponseRedirect(redirect_url)
    else:
        redirect_url = reverse('quizorder:index')  # 'hata_sayfasi' isimli URL'nin adını projenize göre değiştirin
        # Yönlendirme yapın
        return HttpResponseRedirect(redirect_url)

# def exam_edit(request,edit_):
#     print(edit_)
#     edit = Exam.objects.filter(Q(author=request.user) & Q(Exam_Title=edit_))
#     # for edi in edit:
#     #     print("Sınav => ",edi.Question,"Cevap =>",edi.Answer)
#     context={
#         'edit':edit
#     }
#     return render(request,"exam/exam_edit.html",context)


edit_value = None  # Daha yüksek bir kapsamda tanımlanıyor

def exam_edit(request, edit_):
    user = get_object_or_404(Profile, author_id=request.user.id)
     
    if request.user.is_authenticated:
        if user.user_types =="Teacher":

            print(edit_)
            global edit_value  # `edit_` değerini ekrana yazdırın
            edit_value = edit_  # İstenen değeri `edit_degeri` değişkenine atayın
            print("yeni", edit_value)
            edit = Exam.objects.filter(Q(author=request.user) & Q(Exam_Title=edit_))
            context = {
                'edit': edit
            }
            return render(request, "exam/exam_edit.html", context)


        else:
            redirect_url = reverse('quizorder:index')  # 'hata_sayfasi' isimli URL'nin adını projenize göre değiştirin
            # Yönlendirme yapın
            return HttpResponseRedirect(redirect_url)
    else:
        redirect_url = reverse('quizorder:index')  # 'hata_sayfasi' isimli URL'nin adını projenize göre değiştirin
        # Yönlendirme yapın
        return HttpResponseRedirect(redirect_url)





def exam_edit_delete(request, id):
    user = get_object_or_404(Profile, author_id=request.user.id)
     
    if request.user.is_authenticated:
        if user.user_types =="Teacher":
            global edit_value  # Daha yüksek kapsamdaki `edit_degeri`'yi kullanın
            print("yeni", edit_value)
            edit_delete = Exam.objects.filter(Q(author=request.user) & Q(Exam_Title=edit_value)& Q(Question_ID=id))
            if edit_delete.exists():
                edit_delete.delete()
                messages.success(request, "Soru silme işlemi başarılı bir şekilde gerçekleştirildi")
            else:
                messages.error(request, "Soru silinemedi.")

            #return render(request, "exam/exam_edit.html")
            return redirect("cart:exam_edit",edit_value)
        else:
            redirect_url = reverse('quizorder:index')  # 'hata_sayfasi' isimli URL'nin adını projenize göre değiştirin
            # Yönlendirme yapın
            return HttpResponseRedirect(redirect_url)
    else:
        redirect_url = reverse('quizorder:index')  # 'hata_sayfasi' isimli URL'nin adını projenize göre değiştirin
        # Yönlendirme yapın
        return HttpResponseRedirect(redirect_url)




def exam_delete(request, delete):
    user = get_object_or_404(Profile, author_id=request.user.id)
     
    if request.user.is_authenticated:
        if user.user_types =="Teacher":
            edit_delet = Exam.objects.filter(Q(author=request.user) & Q(Exam_Title=delete))
            if edit_delet.exists():
                edit_delet.delete()
                messages.success(request, "Soru silme işlemi başarılı bir şekilde gerçekleştirildi")
            else:
                messages.error(request, "Soru silinemedi.")

            #return render(request, "exam/exam_edit.html")
            return redirect("cart:cart_exam_show")

        else:
            redirect_url = reverse('quizorder:index')  # 'hata_sayfasi' isimli URL'nin adını projenize göre değiştirin
            # Yönlendirme yapın
            return HttpResponseRedirect(redirect_url)
    else:
        redirect_url = reverse('quizorder:index')  # 'hata_sayfasi' isimli URL'nin adını projenize göre değiştirin
        # Yönlendirme yapın
        return HttpResponseRedirect(redirect_url)


def exam_pdf(request,e_title):
    user = get_object_or_404(Profile, author_id=request.user.id)
     
    if request.user.is_authenticated:
        if user.user_types =="Teacher":
            pdf = Exam.objects.filter(Q(author=request.user) & Q(Exam_Title=e_title))
            
            
            context={
                'pdf':pdf,

                
            }
            return render(request,"exam/exam_pdf.html",context)

        else:
            redirect_url = reverse('quizorder:index')  # 'hata_sayfasi' isimli URL'nin adını projenize göre değiştirin
            # Yönlendirme yapın
            return HttpResponseRedirect(redirect_url)
    else:
        redirect_url = reverse('quizorder:index')  # 'hata_sayfasi' isimli URL'nin adını projenize göre değiştirin
        # Yönlendirme yapın
        return HttpResponseRedirect(redirect_url)

templates/cart/cart_albums.html
  <!-- exam name - exam save -->
  <form id="myFormSave"     enctype="multipart/form-data">

  </div>
    <div class="album py-5 bg-light container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-2">
        <div class="col-md">
          <div class="input-group ">
            <span class="input-group-text" id="addon-wrapping">Sınav Adı</span>
            <input type="text" class="form-control" placeholder="" name="input" aria-label="Sınav adı Giriniz" aria-describedby="addon-wrapping">
            <button class="btn btn-primary BTNSUBMIT" type="button" id="button-addon2">Kaydet <i class="bi bi-check-circle"></i></button>
          </div>
          <div id="messageDiv" class="text-center"></div>
      </div>
    
      <div class="col-md">
        <div class="input-group">
          <label class="input-group-text" for="inputGroupSelect01">Sınav Adı Seçiniz</label>
          <select  class="form-select InputGroupSelect1 text-center" id="InputGroupSelect1" aria-label="Example select with button addon">
            {% for title in exam_title %}
            <option value='{{title.exam_title }}'>{{title.exam_title }} </option>
    
    {% endfor %}
        </select>
    
    
        </div>
      </div>
    
    </div>
    </div>
    </form>
      <!-- exam name - exam save -->

<div class="album  mb-5 bg-light container">
  {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">
        {% for cart_show in cart_shows %}
        <div class="col">
            <div class="card shadow-sm">
              {% if cart_show.Question_Image %}
              <img class="card-img-top" src="{{cart_show.Question_Image.url }}" id="Question_Image" name="Question_Image"  width="100%" height="225" alt="..." />
  
              {% else %}
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="40%" y="50%" fill="#eceeef" dy=".3em">Resim Yok</text></svg>
  
              {% endif %}
              <div class="card-body">
                  <span class="badge text-bg-primary">{{ cart_show.Lessons}}</span>
                  <span class="badge text-bg-secondary">{{ cart_show.Topics_Name}}</span>
                  <span class="badge rounded-pill text-bg-danger">{{ cart_show.Level}}</span>
                <p class="card-text">
                  <span class="badge text-bg-info">Soru</span>
                  {{ cart_show.Question}}</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <a class="btn btn-sm btn-outline-success" href="{% url "question:question_detail" cart_show.exam_items %}">Görüntüle</a>
                    {% comment %} <button type="button" class="btn btn-sm btn-outline-success">Görüntüle</button> {% endcomment %}
                   <button type="button" class="btn btn-sm btn-outline-warning BTNALL"  data-user-id="{{cart_show.exam_items}}">Sınava Ekle{{cart_show.exam_items}}</button> 
                   {% comment %} <button type="button" class="btn btn-sm btn-outline-danger">Sil</button>  {% endcomment %}
                   {% comment %} <a class="btn btn-sm btn-outline-danger" href="{% url "question:question_delete" user.id %}">
                    Sil
                  </a> {% endcomment %}
  
                  <a class="btn btn-sm btn-outline-danger cart_delete_Button" href="{% url "question:exam_save_2_cart_delete" cart_show.exam_items %}" data-user-id="{{cart_show.exam_items}}"> Sil</a>
                  </div>
                  <small class="text-muted small">{{ cart_show.Created_Date}}</small>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
        
     


      </div>
    </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function () {
      // Add an event listener to the BTNSUBMIT button
  
      $('.BTNSUBMIT').click(function () {
          var inputValue = $('input[name="input"]').val();
  
          // Send the input value using Ajax
          $.ajax({
              type: 'POST',
              url: "{% url 'question:save_input_value' %}",
              // Replace with your actual URL
              data: {
                  'input': inputValue
              },
              success: function(response) {
                // Handle the response here
                $('#messageDiv').text('Sınav kaydedildi!');
                populateExamTitles();  // Update this with appropriate success message
              },
              error: function(error) {
                console.error('Error:', error);
              },

          });

          
      });

      function populateExamTitles() {
        // Make an AJAX request to get exam titles
        $.ajax({
          url: "{% url 'question:get_exam_titles' %}",
          // Replace with the actual URL of your view
          type: 'GET',
          dataType: 'json',
          success: function(data) {
            // Populate the dropdown with exam titles
            var dropdown = $('#InputGroupSelect1');
             dropdown.empty();
            // dropdown.append('<option value="">Sınav Adı Seçiniz...</option>');
            $.each(data.exam_titles, function(index, title) {
              dropdown.append($('<option></option>').attr('value', title).text(title));
            });
          },
          error: function(error) {
            console.error('Error fetching exam titles:', error);
          }
        });
      }
  });

  $(document).ready(function () {
    $('.BTNALL').on('click', function () {
      var userId = $(this).data('user-id');
    var examTitleId = $('#InputGroupSelect1').val();

      $.ajax({
        type: 'POST',
        url: '{% url "question:exam_save_2" %}',
        data: {
          'user_id': userId,
          'exam_title_id': examTitleId,

          csrfmiddlewaretoken: '{{ csrf_token }}' // CSRF tokenını ekleyin
        },
        success: function (data) {
          //console.log(data.message);
          if (data.success) {
            var message = '' + data.success +' '+ data.exam_title_id;

            displayAlertPopup(message);
          } else {
            alert('Eklenemedi');
          }
        },
        error: function (xhr, status, error) {
          console.log(error);
        }
      });
      function displayAlertPopup(message) {
        // Create a custom alert popup
        var popup = $('<div class="custom-popup bg-success text-white text-uppercase">' + message + '<i class="bi bi-check2-circle"></i></div>');
        
        // Append the popup to the body
        $('body').append(popup);
        
        // Display the popup
        popup.fadeIn();
        
        // Hide the popup after 2 seconds (you can adjust the duration)
        setTimeout(function() {
          popup.fadeOut(function() {
            // Remove the popup from the DOM after fading out
            $(this).remove();
          });
        }, 2000);
      }
    });
  });

  $(document).ready(function() {
    // Call the function to populate exam titles dropdown
    populateExamTitles();
    
  });
  $(document).ready(function(){
    $(".cart_delete_Button").click(function(){
      // Uyarı mesajını değiştirmek isterseniz, displayAlertPopup fonksiyonuna istediğiniz mesajı iletebilirsiniz.
      var message = "Ürün sepetinizden başarıyla silindi. ";

      displayAlertPopup(message);
    });
  
    function displayAlertPopup(message) {
      // Özel bir uyarı popup'ı oluştur
      var popup = $('<div class="custom-popup bg-success text-white text-uppercase">' + message + '<i class="bi bi-check2-circle"></i></div>');
      
      // Popup'ı body içine ekleyin
      $('body').append(popup);
      
      // Popup'ı görüntüle
      popup.fadeIn();
      
      // 2 saniye sonra popup'ı gizle (süreyi isteğinize göre ayarlayabilirsiniz)
      setTimeout(function() {
        popup.fadeOut(function() {
          // Popup gizlendikten sonra DOM'dan kaldırın
          $(this).remove();
        });
      }, 3000);
    }
  });
  
  
</script>
<style>
  .custom-popup {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    background-color: #f9f9f9;
    color: #333;
    padding: 20px;
    border: 1px solid #ccc;
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
    border-radius: 10px;
    max-width: 300px;
    text-align: center;
    font-size: 16px;
    font-family: Arial, sans-serif;
  }
  
  .custom-popup button {
    display: block;
    margin-top: 15px;
    padding: 10px 20px;
    background-color: #3498db;
    color: #fff;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    font-size: 14px;
    font-family: Arial, sans-serif;
  }
  
  .custom-popup button:hover {
    background-color: #2980b9;
  }
  
</style>

templates/cart/cart_show.html
{% include 'base/layout.html' %}
{% comment %} {% include 'base/albums.html' %} {% endcomment %}
{% block body %}
{% include 'cart/cart_albums.html' %}





{% endblock body %}
{% include 'base/footer.html' %}

templates/cart/exam_albums.html


<div class="album py-5 mb-5 bg-light">
  {% if exam_show %}
  <div class="alert alert-warning alert-dismissible fade show container text-center" role="alert">
    {% comment %} <strong>Holy guacamole!</strong>{% endcomment %}Sınavları <strong>Pdf</strong> haline getirmek için sınav isimlerine tıklayınız. 
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% else %}
  {% endif %}

  
<table class="table table-striped table-hover container" >
    <thead>
      <tr class="text-center">
        <th scope="col">Tarih</th>
        <th scope="col">Sınav Adı</th>
        <th scope="col">Sınavı Düzenle</th>
        <th scope="col">Sınavı Sil</th>
      </tr>
    </thead>
    <tbody>
      {% if exam_show %}
    {% for ex in exam_show %}
      <tr class="text-center">
        <th scope="row">{{ex.max_created_date|date:"Y-m-d"}}</th>
        
        <td> <a href="{% url "cart:exam_pdf" ex.Exam_Title %}"  class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">{{ex.Exam_Title}}</a></td>
        <td><a href="{% url "cart:exam_edit" ex.Exam_Title %}"  class="link-primary  link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Düzenle</a></td>

        <td ><a class="link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover " href="{% url "cart:exam_delete" ex.Exam_Title %}">Sil</a></td>
      
      </tr>

      {% endfor %}
      {% else %}
      <tr class="text-center ">
        <td colspan="4 " class="bg-danger text-white">
            Herhangi bir sınavınız yok
        </td>
    </tr>
    
      {% endif %}

    </tbody>
  </table>
</div>


<script>
  var popover = new bootstrap.Popover(document.querySelector('.popover-dismiss'), {
    trigger: 'focus'
  });
</script>

templates/cart/exam_show.html
{% include 'base/layout.html' %}
{% comment %} {% include 'base/albums.html' %} {% endcomment %}
{% block body %}
{% include 'cart/exam_albums.html' %}





{% endblock body %}
{% include 'base/footer.html' %}