cart/urls.py
from django.urls import path
from .import views

app_name="cart"
urlpatterns = [

    path('cart/', views.cart_add, name='cart_add'),
    # path('cart_show/', views.cart_show, name='cart_show'),
    path('cart_exam_show/', views.cart_exam_show, name='cart_exam_show'),
    path('exam_edit/<str:edit_>/', views.exam_edit, name='exam_edit'),
    path('exam_edit_delete/<int:id>/', views.exam_edit_delete, name='exam_edit_delete'),
    path('exam_delete/<str:delete>/', views.exam_delete, name='exam_delete'),
    path('exam_pdf/<str:e_title>/', views.exam_pdf, name='exam_pdf'),

]

main/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings #add this
from django.conf.urls.static import static #add this
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizbox.urls')),
    path('user/', include("user.urls")),    
    path('question/', include("question.urls")),    
    path('cart/', include("cart.urls")),
    path('testing_and_exam/', include("testing_and_exam.urls")),
    path('forum/', include("forum.urls")),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testing_and_exam/urls.py
from django.urls import path
from .import views

app_name="testing_and_exam"
urlpatterns = [
    path('get_elapsed_time/', views.get_elapsed_time, name='get_elapsed_time'),
    path('testing_and_exam/', views.testing_and_exam, name='testing_and_exam'),

    #TESTTİNG URLS
    path('testing/', views.testing, name='testing'),
    path('show_testing/<str:Testing_Name>/', views.show_testing, name='show_testing'),
    path('result_testing/', views.result_testing, name='result_testing'),
    path('testing_result_show/', views.testing_result_show, name='testing_result_show'),
    path('testing_show_result_details/<str:Testing_Name>/', views.testing_show_result_details, name='testing_show_result_details'),
    path('show_testing_istatistic/', views.show_testing_istatistic, name='show_testing_istatistic'),

#-------------------------------------------------------------------------------------------------------------------------------------------# 
    #EXAM URLS
    path('exam_/', views.exam_, name='exam_'),
    path('show_exam_/<str:Exam_Name>/', views.show_exam_, name='show_exam_'),
    path('result_exam/', views.result_exam, name='result_exam'),
    path('exam_result_show/', views.exam_result_show, name='exam_result_show'),
    path('show_exam_result_details/<str:Exam_Name>/', views.show_exam_result_details, name='show_exam_result_details'),
    path('show_exam_istatistic/', views.show_exam_istatistic, name='show_exam_istatistic'),
#-------------------------------------------------------------------------------------------------------------------------------------------# 
    #AYT URLS
    path('ayt/', views.ayt, name='ayt'),
    path('ayt_show/<int:EXAM_Name>/', views.ayt_show, name='ayt_show'),
    path('ayt_result_show/', views.ayt_result_show, name='ayt_result_show'),
    path('ayt_result/', views.ayt_result, name='ayt_result'),
    path('ayt_show_result_details/<str:Date_Choice>/', views.ayt_show_result_details, name='ayt_show_result_details'),
    path('show_ayt_istatistic/', views.show_ayt_istatistic, name='show_ayt_istatistic'),
    


#-------------------------------------------------------------------------------------------------------------------------------------------# 
    #TYT URLS
    path('tyt/', views.tyt, name='tyt'),
    path('show_tyt/<int:EXAM_Name>/', views.show_tyt, name='show_tyt'),
    path('tyt_result_show/', views.tyt_result_show, name='tyt_result_show'),
    path('result_tyt/', views.result_tyt, name='result_tyt'),
    path('show_tyt_result_details/<str:Date_Choice>/', views.show_tyt_result_details, name='show_tyt_result_details'),

    path('show_tyt_istatistic/', views.show_tyt_istatistic, name='show_tyt_istatistic'),

]

exam/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Exam(models.Model):
    author=models.ForeignKey(User,on_delete = models.CASCADE,verbose_name="Soruyu Yazan",default=0)# bunu django hazır kullanıcı tablosundan alıyoruz
    Lessons=models.CharField(verbose_name="Ders Adı",null=True,max_length=50,default=0)
    Exam_Title=models.CharField(verbose_name="Sınav Adı",null=True,max_length=50,default=0)
    Question=models.TextField(verbose_name="Soru",blank=True, null=True)
    Choice_A=models.TextField(verbose_name="A Şıkkı",blank=True, null=True)
    Choice_B=models.TextField(verbose_name="B Şıkkı",blank=True, null=True)
    Choice_C=models.TextField(verbose_name="C Şıkkı",blank=True, null=True)
    Choice_D=models.TextField(verbose_name="D Şıkkı",blank=True, null=True)
    Choice_E=models.TextField(verbose_name="E Şıkkı",blank=True, null=True)
    Answer=models.TextField(verbose_name="Cevap",blank=True, null=True)
    Classroom=models.CharField(verbose_name="Kaçıncı Sınıf Sorusu?",null=True,blank=False,max_length=10,default=0)
    Topics_Name=models.CharField(max_length=100,verbose_name="Konu Adı",null=True,default=0)
    Question_Types=models.CharField(verbose_name='SORU TİPLERİ',null=True,max_length=20,default=0)
    Level = models.CharField(max_length=6, blank=True,default=0)
    Question_ID = models.CharField(max_length=30, blank=True,default=0)
    Question_Image=models.ImageField(upload_to='question_images/',blank=True, null=True, verbose_name="Soruya Fotoğraf Ekleyin")
    Created_Date=models.DateTimeField(auto_now=True,verbose_name="Oluşturma Tarihi")

    def author_id(self):
        return self.author
    def __str__(self):
        return  'author={0}, title={1}'.format(self.author, self.Question)#self.title,self.content,self.created_date



exam/views.py
from django.shortcuts import render

# Create your views here.

testing_and_exam/views.py
from django.shortcuts import redirect, render
from datetime import datetime
from .models import Question_Choice,Exam_Result, Exam_Table, TIMER_S, Testing_Choice, TIMER_S_TESTTING,Testing_Table,Testing_Result,TYT_Choice,TIMER_S_TYT,TYT_Table,TYT_Result,AYT_Choice,AYT_TIMER_S,AYT_Table,AYT_Result
# Create your views here.
from django.contrib import messages
from django.http import HttpResponse, HttpResponseNotAllowed
from django.db.models import Q
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import time
from django.shortcuts import get_object_or_404

def testing_and_exam(request):
    return render(request,"testing_and_exam/testing_and_exam.html")

#DENEME WIEWS ALANI BAŞLANGIÇ
def testing(request):
    if request.user.is_authenticated:
        if request.method == 'GET':

            class_choice = ("9. Sınıf","10. Sınıf","11. Sınıf","12. Sınıf")
            Lessons_choice  = ('Matematik','Biyoloji','Kimya','Fizik','Tarih','Coğrafya','İngilizce','Türk Dili ve Edebiyatı','Din Kültürü ve Ahlak Bilgisi')

            context={
                'class_choice':class_choice,
                'Lessons_choice':Lessons_choice
            }
            return render(request,"testing_and_exam/testing.html",context)
        if request.method == 'POST':
            class_choice = ("9. Sınıf","10. Sınıf","11. Sınıf","12. Sınıf")
            Lessons_choice  = ('Matematik','Biyoloji','Kimya','Fizik','Tarih','Coğrafya','İngilizce','Türk Dili ve Edebiyatı','Din Kültürü ve Ahlak Bilgisi')
            class_choice_ = request.POST.get('sinif')
            Lessons_choice_ = request.POST.get('ders')
            All_Test = Testing_Choice.objects.filter(Q(Class_Choice=class_choice_) & Q(Lessons_Name=Lessons_choice_))
            cnt = All_Test.count()

            context={
                'class_choice':class_choice,
                'Lessons_choice':Lessons_choice,
                'All_Test':All_Test,
                'cnt':cnt
            }

            return render(request,"testing_and_exam/testing.html",context)

    else:
        messages.error(request, "Denemeleri Görüntüleyebilmek İçin Oturum Açınız...")
        return render(request,"testing_and_exam/testing_and_exam.html")
    

def show_testing(request,Testing_Name):
    if request.user.is_authenticated:
        Exam_Name_Filter = Testing_Choice.objects.filter(Testing_Name=Testing_Name)
        Exam_Time_All = get_object_or_404(TIMER_S_TESTTING, Testing_Name=Testing_Name)

        #Exam_Time_All = TIMER_S.objects.all()
        cnt = Exam_Name_Filter.count()
        context={
            'Exam_Name_Filter':Exam_Name_Filter,
            'cnt':cnt,
            'Exam_Time_All':Exam_Time_All
        }
        return render(request,"testing_and_exam/show_testing.html",context)
    else:

        return redirect("testing_and_exam:testing_and_exam")


def result_testing(request):
    if request.method == 'POST':
        # AJAX isteği ile gönderilen verileri alma
        selected_choices_str = request.POST.get('selectedChoices', '')
        elapsed_time = request.POST.get('elapsed_time')
        print("süreeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",elapsed_time)
        # elapsed_minutes = request.POST.get('elapsedMinutes')
        # elapsed_seconds = request.POST.get('elapsedSeconds')
        # print(f"Elapsed Minutes: {elapsed_minutes}")
        # print(f"Elapsed Seconds: {elapsed_seconds}")


        try:
            # JSON formatındaki veriyi Python dictionary'ye çevirme
            selected_choices = json.loads(selected_choices_str)
            user=request.user
            cevap_yanlis_sayisi = 0
            cevap_dogru_sayisi = 0
            cevap_bos_sayisi = 0
            ders=""
            # Seçenekleri ekrana yazdırma (örnek olarak, konsola yazdırma)
            for question_id, choice in selected_choices.items():
                print(f"Question ID: {question_id}, Selected Choice: {choice}")
                print(question_id,choice)
                _result_=Testing_Choice.objects.all()

                #_result_=Question_Choice.objects.filter(id=question_id,Answer_Choice=choice)
                _result_true = _result_.filter(Q(id=question_id) & Q(Answer_Choice=choice))
                _result_false = _result_.filter(Q(id=question_id) & ~Q(Answer_Choice=choice))
                

                su_an = datetime.now()


                if _result_true.exists():
                    for result in _result_true:
                        print("SSSSSSSSSSSSSSSSSSSSSSSS", result.Answer_Choice)
                        print("Cevap Doğru")
                        _result_save = Testing_Result(
                            author=user,
                            Testing_Name=result.Testing_Name,
                            Question_Id=question_id,
                            Question_Key=result.Answer_Choice,
                            author_Key=choice,
                            True_Answer=1
                        )
                        _result_save.save()
                        cevap_dogru_sayisi += 1
                        ders=result.Testing_Name
                else:
                    if choice == "N":
                        for item3 in _result_false:
                            print("Cevap Boş")
                            _result_save3 = Testing_Result(
                                author=user,
                                Testing_Name=item3.Testing_Name,
                                Question_Id=question_id,
                                Question_Key=item3.Answer_Choice,
                                author_Key=choice,
                                True_Answer=2
                            )
                            _result_save3.save()
                            cevap_bos_sayisi += 1
                            ders=item3.Testing_Name
                    else:
                        if _result_false.exists():
                            for item2 in _result_false:
                                print("Cevap Yanlış")
                                _result_save2 = Testing_Result(
                                    author=user,
                                    Testing_Name=item2.Testing_Name,
                                    Question_Id=question_id,
                                    Question_Key=item2.Answer_Choice,
                                    author_Key=choice,
                                    True_Answer=0
                                )
                                _result_save2.save()
                                cevap_yanlis_sayisi += 1
                                ders=item2.Testing_Name

            print("Cevap Doğru Sayısı:", cevap_dogru_sayisi)
            print("Cevap Yanlış Sayısı:", cevap_yanlis_sayisi)
            print("Cevap Boş Sayısı:", cevap_bos_sayisi)
            _total_ = cevap_bos_sayisi + cevap_dogru_sayisi + cevap_yanlis_sayisi
            exam_table_save=Testing_Table.objects.create(
                author=user,
                Testing_Name=ders,
                Total_Number_Of_Questions=_total_,
                Number_Of_True=cevap_dogru_sayisi,
                Number_Of_False=cevap_yanlis_sayisi,
                Number_Of_Empty=cevap_bos_sayisi,
                Testing_Score=6,
                Testing_Rating=10,
                Completion_Time=elapsed_time,
                #Completion_Time= SINAV BİTİRME SÜRESİ GELECEK
                Testing_Date=su_an,
            )
            exam_table_save.save()
            # Başarılı bir şekilde işlendiğine dair bir JSON yanıt gönderme
            #return redirect('quizorder:index')
            return JsonResponse({'message': 'Veriler başarıyla işlendi.'})
        except json.JSONDecodeError:
            # JSON decode hatası durumunda hata mesajı gönderme
            return JsonResponse({'error': 'Veri çözümlenemedi.'}, status=400)

    # POST isteği değilse veya herhangi bir hata oluşursa boş bir JSON yanıt gönderme
    return JsonResponse({})




def testing_result_show(request):
    if request.user.is_authenticated:
        user=request.user
        #exam_finif = get_object_or_404(Exam_Table, author=user)
        exam_finif = Testing_Table.objects.filter(author=user).order_by('-id')
        cnt=exam_finif.count()


        context ={
            'exam_finif':exam_finif,
            'cnt':cnt
        }
        return render(request,"testing_and_exam/testing_result_show.html",context)
    else:
        return redirect('quizorder:index')


def testing_show_result_details(request, Testing_Name):
    if request.user.is_authenticated:
        user = request.user
        get_questions = Testing_Choice.objects.filter(Testing_Name=Testing_Name)
        exam_results_list = []  # Create an empty list to store exam results
        for get_question2 in get_questions:
            exam_results = Testing_Result.objects.filter(author_id=user, Question_Id=get_question2.pk, Testing_Name=get_question2.Testing_Name)
            for exam_rslt2 in exam_results:
                if get_question2.pk == exam_rslt2.Question_Id:
                    print("evet ")
                    exam_results_list.append(exam_rslt2)  # Append each exam result to the list

        context = {
            'exam_results': exam_results_list,
            'get_questions': get_questions,
        }
        
        return render(request, "testing_and_exam/testing_show_result_details.html", context)

    else:
        return redirect('quizorder:index')









#DENEME WIEWS ALANI BİTİŞ
#-------------------------------------------------------------------------------------------------------------------------------------------#  
#SINAV WIEWS ALANI BAŞLANGIÇ
def exam_(request):
    if request.user.is_authenticated:

templates/testing_and_exam/ayt.html
{% include 'base/layout.html' %}
{% comment %} {% include 'base/albums.html' %} {% endcomment %}
{% block body %}

<div class="container">
  <div class="row">
    <div class="col-md-12">
    <h5 class="font-monospace text-center">ALAN YETERLİLİK 2.OTURUM (AYT) SINAV YILLARI SEÇİMİ</h5>

</div>
<hr>
</div>
</div>



<div class="container  shadow-lg p-3 mb-5 bg-body-tertiary rounded">

  <form method="post" action="{% url 'testing_and_exam:ayt' %}">
      {% csrf_token %}  
      <div class="row">
        <div class="col-md-12 mb-3">
          <h5 class="text-center">YIL SEÇİMİ YAPINIZ </h5>
    
      <select class="form-select form-select-lg text-center" name="year">
          {% for  year, date in period_choice.items %}
              <option value="{{ year  }}">{{ date  }}</option>
          {% endfor %}
      </select>
    </div>


      <button type="submit" class="btn btn-primary btn-lg">Sonuçları Göster</button>
  </form>
</div>

<hr>
<table class="table table-striped table-hover container">
  <thead>
    <tr>
      <th scope="col">Eklenme Tarihi</th>
      <th scope="col">Sınav Adı</th>
      <th scope="col">Sınavı Yükleyen</th>

      <th scope="col">Soru Sayısı</th>
      <th scope="col">İstatistik</th>

    </tr>
  </thead>
  <tbody>
    {% if All_Exam %}
    {% for exam in All_Exam %}
        <tr>
          <th scope="row">{{exam.Created_Date}}</th>
          <td><a href="{% url "testing_and_exam:ayt_show" exam.Date_Choice %}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">{{exam.EXAM_Name}}</a></td>
          <td><a href="#" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">{{exam.author}}</a></td>
    
          <td>{{cnt}}</td>
          <td><a tabindex="0" class="btn btn-sm btn-danger popover-dismiss show-exam-rating" role="button" data-bs-toggle="popover" data-bs-trigger="focus" data-bs-html="true" name="{{exam.EXAM_Name}}"  title="{{exam.EXAM_Name}}" data-bs-content='<strong name="rating">SINAV PUANI: <span class="exam-rating-placeholder">-</span></strong><br><em>Sıralaman:12</em><br><p>Baraj Altı:İyi</p>'>Göster</a></td>
    
        </tr>
        {% endfor %}
        {% else %}
    
        <tr>
          <td colspan="5" class="text-bg-danger text-center"><p>Seçilen kriterlere uygun sınav bulunamadı.</p></td>
        </tr>
        {% endif %}

  </tbody>
</table>
</div>

  <script>
    $(document).ready(function(){
      $('.show-exam-rating').click(function(e){
          e.preventDefault();
          var Date_Choice = $(this).attr('name');
          var csrftoken = $("[name=csrfmiddlewaretoken]").val();  // Get the CSRF token from the cookie
          $.ajax({
              type: 'POST',
              url: '{% url "testing_and_exam:show_ayt_istatistic" %}',
              data: {
                  'csrfmiddlewaretoken': csrftoken,  // Include the CSRF token in the request data
                  'Date_Choice': Date_Choice
              },
              dataType: 'json',
              success: function(response){
                  $('.exam-rating-placeholder').text(response.exam_rating);
              },
              error: function(response){
                  console.log('Error:', response);
              }
          });
      });
  });
  
    </script>



<script>
  document.addEventListener('DOMContentLoaded', function() {
      var popoverTriggerList = [].slice.call(document.querySelectorAll('.popover-dismiss'))
      var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
          return new bootstrap.Popover(popoverTriggerEl, {
              trigger: 'focus'
          })
      })
  })
</script>
<style>
  /* CSS ile buton özelleştirmesi */
  .popover-dismiss {
      background-color: #17a2b8; /* Arka plan rengi */
      color: #fff; /* Metin rengi */
      border-color: #17a2b8; /* Kenarlık rengi */
      border-radius: 10px; /* Kenarlık yuvarlaklığı */
      padding: 10px 20px; /* İç boşluklar */
  }
  .popover-header {
      text-align: center;
  }
  </style>

  {% endblock body %}
{% include 'base/footer.html' %}

templates/testing_and_exam/testing_and_exam.html
{% include 'base/layout.html' %}
{% comment %} {% include 'base/albums.html' %} {% endcomment %}
{% block body %}
<style>
    .ornek-eleman {
        margin-bottom: 100px;
    }
</style>
<div class="container mb-5 ornek-eleman">
  
{% if messages %}
<div class="alert alert-danger  alert-dismissible fade show text-center" role="alert">
  {% for message in messages %}
  <strong {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  {% endfor %}
</div>
{% endif %}
 
<div class="row">
    <div class="col-sm-6 mb-3 mb-sm-0">
      <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">
          <h5 class="card-title text-center">SINAV</h5>
          <p class="card-text">"Online sınav sistemimiz, öğrencilere SINAV sürecini etkili bir şekilde yönetme ve değerlendirme olanağı sunmaktadır."</p>
          <div class="d-grid gap-1">

          <a href="{% url "testing_and_exam:exam_" %}" class="btn btn-block btn-primary  "><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-return-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.5 1.5A.5.5 0 0 0 1 2v4.8a2.5 2.5 0 0 0 2.5 2.5h9.793l-3.347 3.346a.5.5 0 0 0 .708.708l4.2-4.2a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 8.3H3.5A1.5 1.5 0 0 1 2 6.8V2a.5.5 0 0 0-.5-.5"/>
          </svg></a>
        </div>
        </div>
      </div>
    </div>
    <div class="col-sm-6 mb-3 mb-sm-0">
      <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">
          <h5 class="card-title text-center">DENEME</h5>
          <p class="card-text">
            "Online sınav sistemimiz, öğrencilere SINAV sürecini etkili bir şekilde yönetme ve değerlendirme olanağı sunmaktadır."</p>
            <div class="d-grid gap-1">

          <a href="{% url "testing_and_exam:testing" %}"  class="btn btn-block btn-primary "><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-return-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.5 1.5A.5.5 0 0 0 1 2v4.8a2.5 2.5 0 0 0 2.5 2.5h9.793l-3.347 3.346a.5.5 0 0 0 .708.708l4.2-4.2a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 8.3H3.5A1.5 1.5 0 0 1 2 6.8V2a.5.5 0 0 0-.5-.5"/>
          </svg></a>
          </div>

        </div>
      </div>
    </div>
  </div>


  <div class="row mt-3 ">
    <div class="col-sm-6 mb-3 mb-sm-0">
      <div class="card  shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">
          <h5 class="card-title text-center">TYT</h5>
          <p class="card-text">"Online sınav sistemimiz, öğrencilere SINAV sürecini etkili bir şekilde yönetme ve değerlendirme olanağı sunmaktadır."</p>
          <div class="d-grid gap-1">

          <a href="{% url "testing_and_exam:tyt" %}" class="btn btn-block btn-primary "><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-return-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.5 1.5A.5.5 0 0 0 1 2v4.8a2.5 2.5 0 0 0 2.5 2.5h9.793l-3.347 3.346a.5.5 0 0 0 .708.708l4.2-4.2a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 8.3H3.5A1.5 1.5 0 0 1 2 6.8V2a.5.5 0 0 0-.5-.5"/>
          </svg></a>
          </div>

        </div>
      </div>
    </div>
    <div class="col-sm-6 mb-3 mb-sm-0">
      <div class="card  shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">
          <h5 class="card-title text-center">AYT</h5>
          <p class="card-text">
            "Online sınav sistemimiz, öğrencilere SINAV sürecini etkili bir şekilde yönetme ve değerlendirme olanağı sunmaktadır."</p>
            <div class="d-grid gap-1">

          <a href="{% url "testing_and_exam:ayt" %}"  class="btn btn-block btn-primary "><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-return-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.5 1.5A.5.5 0 0 0 1 2v4.8a2.5 2.5 0 0 0 2.5 2.5h9.793l-3.347 3.346a.5.5 0 0 0 .708.708l4.2-4.2a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 8.3H3.5A1.5 1.5 0 0 1 2 6.8V2a.5.5 0 0 0-.5-.5"/>
          </svg></a>
        </div>

        </div>
      </div>
    </div>
  </div>



  <div class="row mt-3 ">
    <div class="col-sm-6 mb-3 mb-sm-0">
      <div class="card  shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">
          <h5 class="card-title text-center">KPSS</h5>
          <p class="card-text">"Online sınav sistemimiz, öğrencilere SINAV sürecini etkili bir şekilde yönetme ve değerlendirme olanağı sunmaktadır."</p>
          <div class="d-grid gap-1">

          <a href="{% url "testing_and_exam:tyt" %}" class="btn btn-block btn-primary "><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-return-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.5 1.5A.5.5 0 0 0 1 2v4.8a2.5 2.5 0 0 0 2.5 2.5h9.793l-3.347 3.346a.5.5 0 0 0 .708.708l4.2-4.2a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 8.3H3.5A1.5 1.5 0 0 1 2 6.8V2a.5.5 0 0 0-.5-.5"/>
          </svg></a>
        </div>

        </div>
      </div>
    </div>
    <div class="col-sm-6 mb-3 mb-sm-0">
      <div class="card  shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">
          <h5 class="card-title text-center">ALS</h5>
          <p class="card-text">
            "Online sınav sistemimiz, öğrencilere SINAV sürecini etkili bir şekilde yönetme ve değerlendirme olanağı sunmaktadır."</p>
            <div class="d-grid gap-1">
          <a href="{% url "testing_and_exam:ayt" %}"  class="btn btn-block btn-primary "><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-return-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.5 1.5A.5.5 0 0 0 1 2v4.8a2.5 2.5 0 0 0 2.5 2.5h9.793l-3.347 3.346a.5.5 0 0 0 .708.708l4.2-4.2a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 8.3H3.5A1.5 1.5 0 0 1 2 6.8V2a.5.5 0 0 0-.5-.5"/>
          </svg></a>
          </div>

        </div>
      </div>
    </div>
  </div>

</div>
<div class="ornek-eleman">
  </div>

{% endblock body %}
{% include 'base/footer.html' %}