cart/urls.py
from django.urls import path
from .import views

app_name="cart"
urlpatterns = [

    path('cart/', views.cart_add, name='cart_add'),
    # path('cart_show/', views.cart_show, name='cart_show'),
    path('cart_exam_show/', views.cart_exam_show, name='cart_exam_show'),
    path('exam_edit/<str:edit_>/', views.exam_edit, name='exam_edit'),
    path('exam_edit_delete/<int:id>/', views.exam_edit_delete, name='exam_edit_delete'),
    path('exam_delete/<str:delete>/', views.exam_delete, name='exam_delete'),
    path('exam_pdf/<str:e_title>/', views.exam_pdf, name='exam_pdf'),

]

main/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings #add this
from django.conf.urls.static import static #add this
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizbox.urls')),
    path('user/', include("user.urls")),    
    path('question/', include("question.urls")),    
    path('cart/', include("cart.urls")),
    path('testing_and_exam/', include("testing_and_exam.urls")),
    path('forum/', include("forum.urls")),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

question/urls.py
from django.urls import path
from .import views

app_name="question"

urlpatterns = [
    path('question/',views.Question_,name="Question"),
    path('get_lessons/', views.get_lessons, name='get_lessons'),
    path('get_topics/', views.get_topics, name='get_topics'),
    path('article_create/',views.article_create,name="article_create"),
    path('question_detail/<int:id>/', views.question_detail, name='question_detail'),
    path('question_delete/', views.question_delete, name='question_delete'),
    path('like_question/', views.like_question, name='like_question'),
     path('get_like_count/',  views.get_like_count, name='get_like_count'),
    path('show_cart/', views.show_cart, name='show_cart'),
    path('quiz/', views.quiz, name='quiz'),
    path('save_input_value/', views.save_input_value, name='save_input_value'),
    path('get_exam_titles/', views.get_exam_titles, name='get_exam_titles'),
    
    path('exam_save/', views.exam_save, name='exam_save'),
    path('exam_save_2/', views.exam_save_2, name='exam_save_2'),
    path('exam_save_2_cart_delete//<int:id>/', views.exam_save_2_cart_delete, name='exam_save_2_cart_delete'),
    path('question/<int:question_id>/add_comment/', views.add_comment, name='add_comment'),
    # path('get_topics/', views.get_topics, name='get_topics'),
]

user/urls.py
from django.urls import path
from . import views
app_name="user"
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('login/', views.User_Login, name ='User_Login'),
    path('logout/',views.User_Logout,name="User_Logout"),

    path('register/',views.User_Register, name ='User_Register'),  
    path('activate<uidb64>/<token>/', views.activate, name='activate'),  

    path('profil/<int:pk>/',views.User_Profil,name="User_Profil"),
    path('follow/',views.followView, name="followView"),    
    path('teacher_profiles/',views.teacher_profiles, name="teacher_profiles"),    
    path('profile_question_delete/<int:pk>/',views.profile_question_delete, name="profile_question_delete"),    

    #path('profil/<int:id>/',views.User_Profil,name="Profil"),
    # path('User_Info_Save/',views.User_Info_Save,name="User_Info_Save"),
    path('User_Info_Update/<int:pk>/',views.User_Info_Update,name="User_Info_Update"),

       # Şifre sıfırlama URL'leri
    path('password-reset/',  views.password_reset_request, name='password_reset'),
    path('password-reset/confirm/<uidb64>/<token>/',  views.password_reset_confirm, name='password_reset_confirm'),
    
]

templates/base/albums.html


<style>
  .card-footer .media {
    display: flex;
    align-items: center;
  }

  .card-footer img {
    max-width: 40px;
    margin-right: 15px; /* Adjust the margin as needed */
  }

  .card-footer .media-body {
    text-align: right;
  }
</style>

<div class="album py-2 mb-5 bg-light">
  <div class="container">
    {% if posts %}
    {% for post in posts %}

    <div class="row row-cols-1 row-cols-md-2 g-0 mb-3">
      <div class="col-md-6 container">

        <div class="card ">
          <div class="card-footer border border-1 rounded-top">
            <div class="media justify-content-center">

              {% if post.author_avatar  %}
              <img class="mr-3 rounded-circle" src="{{ post.author_avatar  }}">
              {% else %}
              <img class="mr-3 rounded-circle" src="https://static.vecteezy.com/system/resources/previews/026/219/600/non_2x/account-icon-symbol-design-illustration-vector.jpg?format=auto&version=1688931977&width=80&height=80">
              {% endif %}



              <div class="media-body">
                <h6 class="text-uppercase">

                  <a class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" href="{% url "user:User_Profil" post.author.pk %}">{{ post.author_first_name }} {{ post.author_last_name }}</a>
                </h6>
               


              </div>
            </div>
          </div>

          {% if post.Question_Image %}
          <img src="{{post.Question_Image.url}}" class="card-img-top rounded-0" />
          {% comment %} <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg> {% endcomment %}
					{% else %}
					{% comment %} <img src="https://mocra.org/wp-content/uploads/2016/07/default.jpg" class="card-img-top" alt="..."> {% endcomment %}
          <svg class="bd-placeholder-img card-img-top rounded-0" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="40%" y="50%" fill="#eceeef" dy=".3em">Resim Yok</text></svg> 

					{% endif %}

          <div class="card-body">
            <h5 class="card-title">
              <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#">{{post.Lessons}}</a></li>
                  <li class="breadcrumb-item active" aria-current="page">{{post.Topics_Name}}</li>
                </ol>
              </nav>
            </h5>
            <p class="card-text">
              {{ post.Question}}
            </p>

            <ul class="list-group list-group-light list-group-small text-center">
              <li class="list-group-item px-4 border border-0"><a class="btn btn-sm btn-outline-primary" href="{% url "question:question_detail" post.id %}">Görüntüle</a></li>
              <li class="list-group-item px-4 border border-0"><small class="text-muted small">{{ post.Created_Date}}</small></li>
            </ul>
            

          </div>
          
        </div>
      </div>
    </div>
      {% endfor %}
      {% else %}
      
      
      
      
      {% endif %}

</div>
</div>

templates/base/footer.html
 <!-- <div class=" fixed-bottom bg-body-secondary">
        <footer class="py-3 my-4">
          <ul class="nav justify-content-center ">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
          </ul>
       <p class="text-center text-muted">&copy; 2021 Company, Inc</p>
          <ul class="d-flex justify-content-between py-4 my-4 border-top">
            <li class="ms-3"><a class="link-dark" href="#"><i class="bi bi-twitter"></i></a></li>
            <li class="ms-3"><a class="link-dark" href="#"><i class="bi bi-instagram"></i></a></li>
            <li class="ms-3"><a class="link-dark" href="#"><i class="bi bi-facebook"></i></a></li>
          </ul>
          <div class="d-flex text-muted justify-content-center py-4 my-4 border-top">
            <p>&copy; 2023 Company, Inc. Tüm hakları saklıdır</p>
            <ul class="list-unstyled d-flex">
                <li class="ms-3 "><a class="link-dark icon-link icon-link-hover" href="#"><i class="bi bi-twitter"></i></a></li>
                <li class="ms-3"><a class="link-dark icon-link icon-link-hover" href="#"><i class="bi bi-instagram"></i></a></li>
                <li class="ms-3"><a class="link-dark icon-link icon-link-hover" href="#"><i class="bi bi-facebook"></i></a></li>
            </ul>
          </div>
        </footer>
      </div> -->
      

      <footer class="fixed-bottom bg-light">
        <div class="container py-3">
          <div class="row justify-content-between align-items-center">
            <div class="col-md-4 d-flex align-items-center">
              <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
              </a>
              <span class="text-muted">&copy; 2024 Company, Inc. Cihan İlkılıç</span>

            </div>
    
            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
              <li class="ms-3"><a class="link-dark icon-link icon-link-hover" href="#"><i class="bi bi-twitter"></i></a></li>
              <li class="ms-3"><a class="link-dark icon-link icon-link-hover" href="#"><i class="bi bi-instagram"></i></a></li>
              <li class="ms-3"><a class="link-dark icon-link icon-link-hover" href="#"><i class="bi bi-facebook"></i></a></li>
            </ul>
          </div>
        </div>
      </footer>
{% comment %}     
      <footer class="bg-dark py-4 mt-auto ">
        <div class="container px-5">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; ucuzcebim.com 2023</div></div>
                <div class="col-auto">
                    <a class="link-light small" href=" ">Gizlilik</a>
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" href=" ">Şartlar</a>
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" href=" ">İletişim</a>
                </div>
            </div>
        </div>
    </footer>
     {% endcomment %}

templates/base/layout.html
<!doctype html>
<html lang="tr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>quizkutusu.com</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
  <body>
{% include 'base/navbar.html' %}

    
{% block body %}
<ul id="totalCount"class="py-4 container text-center"></ul>

{% comment %} <ul id="myUL" class="py-1  text-center"></ul> {% endcomment %}



{% if user_post %}


{% else %}




{% endif %}



{% endblock body %}
<!-- Section: Design Block -->

{% comment %} {% include 'base/albums.html' %} {% endcomment %}




   
  </body>
</html>

templates/base/messages.html
{% if messages %}
    {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }} text-center border-0" role="alert" {% endif %}>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}