cart/urls.py
from django.urls import path
from .import views

app_name="cart"
urlpatterns = [

    path('cart/', views.cart_add, name='cart_add'),
    # path('cart_show/', views.cart_show, name='cart_show'),
    path('cart_exam_show/', views.cart_exam_show, name='cart_exam_show'),
    path('exam_edit/<str:edit_>/', views.exam_edit, name='exam_edit'),
    path('exam_edit_delete/<int:id>/', views.exam_edit_delete, name='exam_edit_delete'),
    path('exam_delete/<str:delete>/', views.exam_delete, name='exam_delete'),
    path('exam_pdf/<str:e_title>/', views.exam_pdf, name='exam_pdf'),

]

main/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings #add this
from django.conf.urls.static import static #add this
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizbox.urls')),
    path('user/', include("user.urls")),    
    path('question/', include("question.urls")),    
    path('cart/', include("cart.urls")),
    path('testing_and_exam/', include("testing_and_exam.urls")),
    path('forum/', include("forum.urls")),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

question/urls.py
from django.urls import path
from .import views

app_name="question"

urlpatterns = [
    path('question/',views.Question_,name="Question"),
    path('get_lessons/', views.get_lessons, name='get_lessons'),
    path('get_topics/', views.get_topics, name='get_topics'),
    path('article_create/',views.article_create,name="article_create"),
    path('question_detail/<int:id>/', views.question_detail, name='question_detail'),
    path('question_delete/', views.question_delete, name='question_delete'),
    path('like_question/', views.like_question, name='like_question'),
     path('get_like_count/',  views.get_like_count, name='get_like_count'),
    path('show_cart/', views.show_cart, name='show_cart'),
    path('quiz/', views.quiz, name='quiz'),
    path('save_input_value/', views.save_input_value, name='save_input_value'),
    path('get_exam_titles/', views.get_exam_titles, name='get_exam_titles'),
    
    path('exam_save/', views.exam_save, name='exam_save'),
    path('exam_save_2/', views.exam_save_2, name='exam_save_2'),
    path('exam_save_2_cart_delete//<int:id>/', views.exam_save_2_cart_delete, name='exam_save_2_cart_delete'),
    path('question/<int:question_id>/add_comment/', views.add_comment, name='add_comment'),
    # path('get_topics/', views.get_topics, name='get_topics'),
]

user/urls.py
from django.urls import path
from . import views
app_name="user"
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('login/', views.User_Login, name ='User_Login'),
    path('logout/',views.User_Logout,name="User_Logout"),

    path('register/',views.User_Register, name ='User_Register'),  
    path('activate<uidb64>/<token>/', views.activate, name='activate'),  

    path('profil/<int:pk>/',views.User_Profil,name="User_Profil"),
    path('follow/',views.followView, name="followView"),    
    path('teacher_profiles/',views.teacher_profiles, name="teacher_profiles"),    
    path('profile_question_delete/<int:pk>/',views.profile_question_delete, name="profile_question_delete"),    

    #path('profil/<int:id>/',views.User_Profil,name="Profil"),
    # path('User_Info_Save/',views.User_Info_Save,name="User_Info_Save"),
    path('User_Info_Update/<int:pk>/',views.User_Info_Update,name="User_Info_Update"),

       # Şifre sıfırlama URL'leri
    path('password-reset/',  views.password_reset_request, name='password_reset'),
    path('password-reset/confirm/<uidb64>/<token>/',  views.password_reset_confirm, name='password_reset_confirm'),
    
]

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SignupForm(UserCreationForm):
    email = forms.EmailField(label='E-Posta', max_length=200, help_text='zorunlu')
    username = forms.CharField(label='Kullanıcı Adı', max_length=200, help_text='zorunlu')
    
    first_name = forms.CharField(label='Ad', max_length=30, help_text='adınızı girin')
    last_name = forms.CharField(label='Soyad', max_length=30, help_text='soyadınızı girin')
    phone_number = forms.CharField(label='Telefon Numarası', max_length=15, help_text='telefon numaranızı girin')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'phone_number', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Bu e-posta adresi zaten kullanımda.")
        return email


    # def clean_phone(self):
    #     phone_number = self.cleaned_data['phone_number']
    #     if User.objects.filter(phone_number=phone_number).exists():
    #         raise forms.ValidationError("Bu telefon numarası zaten kullanımda.")
    #     return phone_number

# class LoginForm(forms.Form):
#     username = forms.CharField()
#     password = forms.CharField(widget=forms.PasswordInput)




from django import forms
from django.contrib.auth.forms import SetPasswordForm

class CustomPasswordChangeForm(SetPasswordForm):
    new_password1 = forms.CharField(label="Yeni Şifre", widget=forms.PasswordInput)
    new_password2 = forms.CharField(label="Yeni Şifre Tekrar", widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get("new_password1")
        new_password2 = cleaned_data.get("new_password2")

        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError("The new passwords do not match.")
        return cleaned_data




from django import forms
from.models import *
class User_Update_Forms(forms.ModelForm):
    class Meta:
        model=Profile
        fields=[
        'biographys',
        'mobile_phone',
        'avatars',
        'social_media_facebook',
        'social_media_twitter',
        'social_media_instagram',
        'social_media_tiktok'        
        ]

user/views.py
from django.shortcuts import render
#from .forms import LoginForm
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, HttpResponse, HttpResponseRedirect
from django.core.mail import EmailMessage  
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model
from django.utils.encoding import force_bytes, force_str  
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode  
from .tokens import account_activation_token  
from .forms import *
from django.contrib.sites.shortcuts import get_current_site  
from django.template.loader import render_to_string  
from question.models import Question
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from.models import Profile
from.views import *
from .forms import *
from django.contrib.auth.models import User
from django.db.models import Count
from django.http import Http404, HttpResponse, HttpResponseNotAllowed, HttpResponseRedirect, JsonResponse
from django.db.models import Q



def User_Register(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()  # Save the user first to generate the user ID

            new_user_profile = Profile.objects.create(
                author=user,  # Set the author to the newly created user
                # Add other fields for Profile if needed
            )
            
            new_user_profile.save()
            
            current_site = get_current_site(request)
            mail_subject = 'Aktivasyon bağlantısı e-posta kimliğinize gönderildi'
            message = render_to_string('user/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return render(request, 'user/Email.html', {'msg': 'Kaydı tamamlamak için lütfen e-posta adresinizi doğrulayın'})
    else:
        form = SignupForm()
    return render(request, 'user/register.html', {'form': form, 'title': 'kayıt ol!'})


# # Create your views here.
# def User_Login(request):
#     if request.method == 'POST':
#         form = AuthenticationForm(request, request.POST)
#         if form.is_valid():
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password']
#             user = authenticate(request, username=username, password=password)
#             if user is not None:
#                 login(request, user)
#                 messages.success(request, f'Hoşgeldin {username}!!')
#                 return redirect('quizbox:index')
#             else:
#                 try:
#                     User.objects.get(username=username)
#                     messages.error(request, 'Şifre hatalı!')
#                     return redirect('user:User_Login')

#                 except User.DoesNotExist:
#                     messages.error(request, 'Kullanıcı bulunamadı!')
#                     return redirect('user:User_Login')

#         else:
#             messages.error(request, 'Geçersiz giriş, lütfen kullanıcı adı ve şifreyi kontrol edin.')
#             return redirect('user:User_Login')

#     else:
#         form = AuthenticationForm()
#     return render(request, 'user/login.html', {'form': form, 'title': 'Giriş Yap'})


def User_Login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('user:User_Profil',request.user.id)
        else:
            messages.error(request, 'Geçersiz giriş, lütfen kullanıcı adı ve şifreyi kontrol edin.')
    else:
        form = AuthenticationForm()
    return render(request, 'user/login.html', {'form': form})




def activate(request, uidb64, token):  
    User = get_user_model()  
    try:  
        uid = force_str(urlsafe_base64_decode(uidb64))  
        user = User.objects.get(pk=uid)  
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):  
        user = None
    if user is not None and account_activation_token.check_token(user, token):  
        user.is_active = True
        user.save()  
        return render(request,'user/Email.html',{'msg':'E-posta onayınız için teşekkür ederiz. Artık hesabınıza giriş yapabilirsiniz.'})  
    else:  
        return render(request, 'user/Email.html',{'msg':'Etkinleştirme bağlantısı geçersiz!'})  


def User_Logout(request):
    logout (request)
    return redirect("quizbox:index")



from django.shortcuts import render, redirect
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes

def password_reset_request(request):
    if request.method == "POST":
        email = request.POST['email']
        associated_users = User.objects.filter(email=email)
        if associated_users.exists():
            for user in associated_users:
                subject = "Parola Sıfırlama İsteği"
                email_template_name = "user/password_reset_email.html"
                c = {
                    "email": user.email,
                    "domain": request.META["HTTP_HOST"],
                    "site_name": "Siteniz",
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "user": user,
                    "token": default_token_generator.make_token(user),
                    "protocol": "http",
                }
                email = render_to_string(email_template_name, c)
                send_mail(subject, email, "quizkutusu.com", [user.email], fail_silently=False)
            return HttpResponse('E-posta ile parola sıfırlama bağlantısı gönderildi.')
        else:
            return HttpResponse('Bu e-posta adresiyle ilişkili bir hesap bulunamadı.')
    return render(request, "user/password_reset_form.html")

from django.utils.encoding import force_str

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
def password_reset_confirm(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        if request.method == 'POST':
            form = CustomPasswordChangeForm(user, request.POST)
            if form.is_valid():
                user = form.save()
                # Kullanıcının oturumunu güncelleyin
                update_session_auth_hash(request, user)
                return HttpResponse("Parola başarıyla değiştirildi.")
        else:
            form = CustomPasswordChangeForm(user)
        return render(request, 'user/password_change_form.html', {'form': form})
    else:
        return HttpResponse("Geçersiz parola sıfırlama bağlantısı!")





@login_required
def User_Profil(request, pk):
    # GET işlemi için kullanıcı profilini görüntüleme
    if request.method == 'GET':
        # 'id' parametresi, kullanıcı profilini görüntülemek istediğiniz kullanıcının benzersiz kimliğini temsil eder.
        # Bu kimliği kullanarak veritabanından ilgili kullanıcıyı almanız gerekiyor.

        user_profile = get_object_or_404(Profile, author_id=pk)
        distinct_topics = Question.objects.filter(author_id=pk).values('Topics_Name').annotate(count=Count('Topics_Name'))

        print("----------------------------------------",user_profile.user_types)


        user_post=Question.objects.filter(author_id=pk)

        for post in user_post:
            # Author'ın avatar fotoğrafını al
            author_avatar = None
            author_profile = Profile.objects.filter(author=post.author).first()  # Author'a ait Profile nesnesini al
            if author_profile:
                post.author_avatar_url = author_profile.avatars.url if author_profile.avatars else None

        topic_count = user_post.values('Topics_Name').distinct().count()
        user_post_count=user_post.count()
        user_followers_count=user_profile.followers.count()
        user_following_count=user_profile.following.count()
        for user in user_post:
            print(user,"nabersssssssssssss")

        return render(request, "user/profil.html", {
            'user_profile': user_profile,
            'topics_count':distinct_topics,
            'topic_count': topic_count,
            'user_post':user_post,
            'user_post_count':user_post_count,
            'user_followers_count':user_followers_count,
            'user_following_count':user_following_count

        })

    # POST işlemi için kullanıcı profilini güncelleme
    elif request.method == 'POST':
        # POST isteğiyle gönderilen verileri almak için request.POST kullanabilirsiniz.
        # Örnek olarak, kullanıcının profil bilgilerini güncellemek için form verilerini burada işleyebilirsiniz.

templates/user/acc_active_email.html
{% autoescape off %}  
Merhaba {{ user.get_full_name }}, Quiz Kutusu 
Kaydınızı onaylamak için lütfen aşağıdaki linke tıklayın,  
http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}  
{% endautoescape %}  

templates/user/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Parola Sıfırlama Onayı</title>
</head>
<body>
    <h2>Parola Sıfırlama Onayı</h2>
    {% if valid %}
        <p>Parola sıfırlama bağlantısı doğrulandı.</p>
        <!-- Parola sıfırlama formu veya başka bir işlem buraya eklenebilir -->
    {% else %}
        <p>Geçersiz parola sıfırlama bağlantısı!</p>
    {% endif %}
</body>
</html>

templates/user/profile_questions.html



    <style>
      .card-footer .media {
        display: flex;
        align-items: center;
      }
    
      .card-footer img {
        max-width: 40px;
        margin-right: 15px; /* Adjust the margin as needed */
      }
    
      .card-footer .media-body {
        text-align: right;
      }
    </style>
    
    <div class="album py-2 mb-5 bg-light">
      
      <div class="container">
        {% if user_post %}
        {% for user in user_post %}
    
        <div class="row row-cols-1 row-cols-md-2 g-0 mb-3">
          <div class="col-md-6 container">
    
            <div class="card ">
              
              <div class="card-footer border border-1 rounded-top">
                <div class="media justify-content-center">
                  


                  {% if user.author_avatar_url %}
                  <img class="mr-3 rounded-circle" src="{{ user.author_avatar_url }}">
                  {% else %}
                  <img class="mr-3 rounded-circle" src="https://static.vecteezy.com/system/resources/previews/026/219/600/non_2x/account-icon-symbol-design-illustration-vector.jpg?format=auto&version=1688931977&width=80&height=80">
                  {% endif %}
                  <div class="media-body">
                    <a class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" href="#"><h6 class="text-uppercase">{{user.author.first_name}} {{user.author.last_name}}</h6></a>
                  </div>
                  <!-- Düğme Başlangıç -->
                  {% if request.user.id == user.author.pk %}
                  <div class="dropdown dropstart  justify-content-end">
                    <button class="btn btn-white  btn-ghost btn-icon btn-sm rounded-circle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-vertical icon-xs">
                        <circle cx="12" cy="12" r="1"></circle>
                        <circle cx="12" cy="5" r="1"></circle>
                        <circle cx="12" cy="19" r="1"></circle>
                      </svg>
                    </button>
                   
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton"> 
                      {% comment %} <li><a class="dropdown-item" href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                          <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                          <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                        </svg>Düzenle</a></li> {% endcomment %}
                      <li><a class="dropdown-item" href="{% url "user:profile_question_delete" user.pk %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="red" class="bi bi-trash" viewBox="0 0 16 16">
                          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                          <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                      </svg>
                      Sil{{user.pk}}-----------{{request.user.id}}</a></li>
                    </ul>

                  </div>
                  <!-- Düğme Bitiş -->
                  {% endif %}

                </div>

              </div>
    
              {% if user.Question_Image %}
              <img src="{{user.Question_Image.url}}" class="card-img-top rounded-0" />
              {% comment %} <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg> {% endcomment %}
              {% else %}
              {% comment %} <img src="https://mocra.org/wp-content/uploads/2016/07/default.jpg" class="card-img-top" alt="..."> {% endcomment %}
              {% comment %} <svg class="bd-placeholder-img card-img-top rounded-0" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="40%" y="50%" fill="#eceeef" dy=".3em">Resim Yok</text></svg>  {% endcomment %}
    
              {% endif %}
    
              <div class="card-body">
                <h5 class="card-title">
                  <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item"><a href="#">{{user.Lessons}}</a></li>
                      <li class="breadcrumb-item active" aria-current="page">{{user.Topics_Name}}</li>
                    </ol>
                  </nav>
                </h5>
                <p class="card-text">
                  {{ user.Question}}
                </p>
    
                <ul class="list-group list-group-light list-group-small text-center">
                  <li class="list-group-item px-4 border border-0"><a class="btn btn-sm btn-outline-primary" href="{% url "question:question_detail" user.id %}">Görüntüle</a></li>
                  <li class="list-group-item px-4 border border-0"><small class="text-muted small">{{ user.Created_Date}}</small></li>
                </ul>
                
  

              </div>
              
            </div>
          </div>
        </div>
          {% endfor %}
          {% else %}
          
          
          
          
          {% endif %}
    
    </div>
    </div>











  </div>







  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
  
$(document).ready(function() {
  $('.saveButton').click(function(event) {
    event.preventDefault();
    var userId = $(this).data('user-id');
    var csrfToken = '{{ csrf_token }}';  // Ensure csrf_token is correctly generated

    $.ajax({
      url: '{% url 'question:question_delete' %}',
      method: 'POST',
      data: {
        'user_id': userId,
        'csrfmiddlewaretoken': csrfToken
      },
      success: function(data) {
        if (data.success) {
          var message = 'başarıyla Silindi';
          displayAlertPopup(message);
        } else {
          alert('Silinemedi');
        }
      }
      
    });
    function displayAlertPopup(message) {
      // Create a custom alert popup
      var popup = $('<div class="custom-popup bg-danger text-white text-uppercase">' + message + '<i class="bi bi-check2-circle"></i></div>');
      
      // Append the popup to the body
      $('body').append(popup);
      
      // Display the popup
      popup.fadeIn();
      
      // Hide the popup after 2 seconds (you can adjust the duration)
      setTimeout(function() {
        popup.fadeOut(function() {
          // Remove the popup from the DOM after fading out
          $(this).remove();
        });
      }, 2000);
    }
    
  });
});

  
    </script>
    <style>
      .custom-popup {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-color: #f9f9f9;
        color: #333;
        padding: 20px;
        border: 1px solid #ccc;
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
        border-radius: 10px;
        max-width: 300px;
        text-align: center;
        font-size: 16px;
        font-family: Arial, sans-serif;
      }
      
      .custom-popup button {
        display: block;
        margin-top: 15px;
        padding: 10px 20px;
        background-color: #3498db;
        color: #fff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 14px;
        font-family: Arial, sans-serif;
      }
      
      .custom-popup button:hover {
        background-color: #2980b9;
      }
      
    </style>






templates/user/register.html
{% include 'base_user/base_user.html' %}
{% block body %}
<div class="container mt-5">
  <div class="row justify-content-center">
      <div class="col-md-6">
          <div class="card ">
              <div class="card-body">
                <div class="card-header bg-primary text-white">
                  <h2 class="text-center">quizkutusu.com/Kayıt Ol</h2>
              </div>
                  <form method="POST" class="p-4">
                      {% csrf_token %}
                      <div class="form-group row">
                          <label for="id_username" class="col-sm-3 col-form-label">Kullanıcı Adı</label>
                          <div class="col-sm-9">
                              {{ form.username }}
                              {% if form.username.errors %}
                                  {% for error in form.username.errors %}
                                      <span class="text-danger">{{ error }}</span>
                                  {% endfor %}
                              {% endif %}
                          </div>
                      </div>
                      <div class="form-group row">
                          <label for="id_first_name" class="col-sm-3 col-form-label">Ad</label>
                          <div class="col-sm-9">
                              {{ form.first_name }}
                              {% if form.first_name.errors %}
                                  {% for error in form.first_name.errors %}
                                      <span class="text-danger">{{ error }}</span>
                                  {% endfor %}
                              {% endif %}
                          </div>
                      </div>
                      <div class="form-group row">
                          <label for="id_last_name" class="col-sm-3 col-form-label">Soyad</label>
                          <div class="col-sm-9">
                              {{ form.last_name }}
                              {% if form.last_name.errors %}
                                  {% for error in form.last_name.errors %}
                                      <span class="text-danger">{{ error }}</span>
                                  {% endfor %}
                              {% endif %}
                          </div>
                      </div>
                      <div class="form-group row">
                          <label for="id_phone_number" class="col-sm-3 col-form-label">Telefon Numarası</label>
                          <div class="col-sm-9">
                              {{ form.phone_number }}
                              {% comment %} {% if form.phone_number.errors %}
                                  {% for error in form.phone_number.errors %}
                                      <span class="text-danger">{{ error }}</span>
                                  {% endfor %}
                              {% endif %} {% endcomment %}
                          </div>
                      </div>
                      <div class="form-group row">
                          <label for="id_email" class="col-sm-3 col-form-label">E-Posta</label>
                          <div class="col-sm-9">
                              {{ form.email }}
                              {% if form.email.errors %}
                                  {% for error in form.email.errors %}
                                      <span class="text-danger">{{ error }}</span>
                                  {% endfor %}
                              {% endif %}
                          </div>
                      </div>
                      <div class="form-group row">
                          <label for="id_password1" class="col-sm-3 col-form-label">Şifre</label>
                          <div class="col-sm-9">
                              {{ form.password1 }}
                              {% if form.password1.errors %}
                                  {% for error in form.password1.errors %}
                                      <span class="text-danger">{{ error }}</span>
                                  {% endfor %}
                              {% endif %}
                          </div>
                      </div>
                      <div class="form-group row">
                          <label for="id_password2" class="col-sm-3 col-form-label">Şifre (Tekrar)</label>
                          <div class="col-sm-9">
                              {{ form.password2 }}
                              {% if form.password2.errors %}
                                  {% for error in form.password2.errors %}
                                      <span class="text-danger">{{ error }}</span>
                                  {% endfor %}
                              {% endif %}
                          </div>
                      </div>
                      <div class="text-center mt-3">
                          <button class="btn btn-primary btn-block col-sm-12 col-12" type="submit"><span class="glyphicon glyphicon-check"></span> Kayıt Ol</button>
                      </div>
                      <div class="mt-3 text-center">
                          <sub><a href="{% url 'user:User_Login' %}"  class="text-primary">Zaten bir hesabınız var mı? Giriş yapın.</a></sub>
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div>
</div>


{% endblock body %}